// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Generated from core/include/lenny/lenny.h. Do not edit.
class LennyBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LennyBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LennyBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int lenny_abi_version() {
    return _lenny_abi_version();
  }

  late final _lenny_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('lenny_abi_version');
  late final _lenny_abi_version = _lenny_abi_versionPtr
      .asFunction<int Function()>();

  int lenny_now_us() {
    return _lenny_now_us();
  }

  late final _lenny_now_usPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>('lenny_now_us');
  late final _lenny_now_us = _lenny_now_usPtr.asFunction<int Function()>();

  int lenny_receiver_approve(ffi.Pointer<lenny_session> s, int accept) {
    return _lenny_receiver_approve(s, accept);
  }

  late final _lenny_receiver_approvePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<lenny_session>, ffi.Int32)
        >
      >('lenny_receiver_approve');
  late final _lenny_receiver_approve = _lenny_receiver_approvePtr
      .asFunction<int Function(ffi.Pointer<lenny_session>, int)>();

  ffi.Pointer<lenny_session> lenny_receiver_create(
    ffi.Pointer<lenny_receiver_config> config,
    ffi.Pointer<lenny_receiver_callbacks> callbacks,
  ) {
    return _lenny_receiver_create(config, callbacks);
  }

  late final _lenny_receiver_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<lenny_session> Function(
            ffi.Pointer<lenny_receiver_config>,
            ffi.Pointer<lenny_receiver_callbacks>,
          )
        >
      >('lenny_receiver_create');
  late final _lenny_receiver_create = _lenny_receiver_createPtr
      .asFunction<
        ffi.Pointer<lenny_session> Function(
          ffi.Pointer<lenny_receiver_config>,
          ffi.Pointer<lenny_receiver_callbacks>,
        )
      >();

  int lenny_receiver_new_pair_token(
    ffi.Pointer<lenny_session> s,
    int ttl_ms,
    ffi.Pointer<ffi.Uint8> out,
  ) {
    return _lenny_receiver_new_pair_token(s, ttl_ms, out);
  }

  late final _lenny_receiver_new_pair_tokenPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint8>,
          )
        >
      >('lenny_receiver_new_pair_token');
  late final _lenny_receiver_new_pair_token = _lenny_receiver_new_pair_tokenPtr
      .asFunction<
        int Function(ffi.Pointer<lenny_session>, int, ffi.Pointer<ffi.Uint8>)
      >();

  int lenny_receiver_port(ffi.Pointer<lenny_session> s) {
    return _lenny_receiver_port(s);
  }

  late final _lenny_receiver_portPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint16 Function(ffi.Pointer<lenny_session>)>
      >('lenny_receiver_port');
  late final _lenny_receiver_port = _lenny_receiver_portPtr
      .asFunction<int Function(ffi.Pointer<lenny_session>)>();

  int lenny_receiver_select_stream(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_stream_settings> preferred,
  ) {
    return _lenny_receiver_select_stream(s, preferred);
  }

  late final _lenny_receiver_select_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_stream_settings>,
          )
        >
      >('lenny_receiver_select_stream');
  late final _lenny_receiver_select_stream = _lenny_receiver_select_streamPtr
      .asFunction<
        int Function(
          ffi.Pointer<lenny_session>,
          ffi.Pointer<lenny_stream_settings>,
        )
      >();

  int lenny_receiver_send_control(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_control> control,
  ) {
    return _lenny_receiver_send_control(s, control);
  }

  late final _lenny_receiver_send_controlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_control>,
          )
        >
      >('lenny_receiver_send_control');
  late final _lenny_receiver_send_control = _lenny_receiver_send_controlPtr
      .asFunction<
        int Function(ffi.Pointer<lenny_session>, ffi.Pointer<lenny_control>)
      >();

  int lenny_receiver_start(ffi.Pointer<lenny_session> s) {
    return _lenny_receiver_start(s);
  }

  late final _lenny_receiver_startPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<lenny_session>)>
      >('lenny_receiver_start');
  late final _lenny_receiver_start = _lenny_receiver_startPtr
      .asFunction<int Function(ffi.Pointer<lenny_session>)>();

  int lenny_receiver_trust_device(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<ffi.Uint8> device_id,
  ) {
    return _lenny_receiver_trust_device(s, device_id);
  }

  late final _lenny_receiver_trust_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<lenny_session>, ffi.Pointer<ffi.Uint8>)
        >
      >('lenny_receiver_trust_device');
  late final _lenny_receiver_trust_device = _lenny_receiver_trust_devicePtr
      .asFunction<
        int Function(ffi.Pointer<lenny_session>, ffi.Pointer<ffi.Uint8>)
      >();

  int lenny_sender_connect(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<ffi.Char> host,
    int port,
    ffi.Pointer<ffi.Uint8> pair_token,
  ) {
    return _lenny_sender_connect(s, host, port, pair_token);
  }

  late final _lenny_sender_connectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint16,
            ffi.Pointer<ffi.Uint8>,
          )
        >
      >('lenny_sender_connect');
  late final _lenny_sender_connect = _lenny_sender_connectPtr
      .asFunction<
        int Function(
          ffi.Pointer<lenny_session>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Uint8>,
        )
      >();

  ffi.Pointer<lenny_session> lenny_sender_create(
    ffi.Pointer<lenny_sender_config> config,
    ffi.Pointer<lenny_sender_callbacks> callbacks,
  ) {
    return _lenny_sender_create(config, callbacks);
  }

  late final _lenny_sender_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<lenny_session> Function(
            ffi.Pointer<lenny_sender_config>,
            ffi.Pointer<lenny_sender_callbacks>,
          )
        >
      >('lenny_sender_create');
  late final _lenny_sender_create = _lenny_sender_createPtr
      .asFunction<
        ffi.Pointer<lenny_session> Function(
          ffi.Pointer<lenny_sender_config>,
          ffi.Pointer<lenny_sender_callbacks>,
        )
      >();

  int lenny_sender_send_control_state(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_control_state> state,
  ) {
    return _lenny_sender_send_control_state(s, state);
  }

  late final _lenny_sender_send_control_statePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_control_state>,
          )
        >
      >('lenny_sender_send_control_state');
  late final _lenny_sender_send_control_state =
      _lenny_sender_send_control_statePtr
          .asFunction<
            int Function(
              ffi.Pointer<lenny_session>,
              ffi.Pointer<lenny_control_state>,
            )
          >();

  int lenny_sender_send_stream_status(
    ffi.Pointer<lenny_session> s,
    int state,
    ffi.Pointer<ffi.Char> reason,
  ) {
    return _lenny_sender_send_stream_status(s, state, reason);
  }

  late final _lenny_sender_send_stream_statusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Uint8,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('lenny_sender_send_stream_status');
  late final _lenny_sender_send_stream_status =
      _lenny_sender_send_stream_statusPtr
          .asFunction<
            int Function(ffi.Pointer<lenny_session>, int, ffi.Pointer<ffi.Char>)
          >();

  int lenny_sender_send_video_config(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<ffi.Uint8> data,
    int size,
  ) {
    return _lenny_sender_send_video_config(s, data, size);
  }

  late final _lenny_sender_send_video_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('lenny_sender_send_video_config');
  late final _lenny_sender_send_video_config =
      _lenny_sender_send_video_configPtr
          .asFunction<
            int Function(
              ffi.Pointer<lenny_session>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  int lenny_sender_send_video_frame(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<ffi.Uint8> data,
    int size,
    int pts_us,
    int orientation,
    int flags,
  ) {
    return _lenny_sender_send_video_frame(
      s,
      data,
      size,
      pts_us,
      orientation,
      flags,
    );
  }

  late final _lenny_sender_send_video_framePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int64,
            ffi.Uint8,
            ffi.Uint8,
          )
        >
      >('lenny_sender_send_video_frame');
  late final _lenny_sender_send_video_frame = _lenny_sender_send_video_framePtr
      .asFunction<
        int Function(
          ffi.Pointer<lenny_session>,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          int,
        )
      >();

  int lenny_sender_update_stream(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_stream_settings> effective,
  ) {
    return _lenny_sender_update_stream(s, effective);
  }

  late final _lenny_sender_update_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_stream_settings>,
          )
        >
      >('lenny_sender_update_stream');
  late final _lenny_sender_update_stream = _lenny_sender_update_streamPtr
      .asFunction<
        int Function(
          ffi.Pointer<lenny_session>,
          ffi.Pointer<lenny_stream_settings>,
        )
      >();

  int lenny_session_control_state(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_control_state> out,
  ) {
    return _lenny_session_control_state(s, out);
  }

  late final _lenny_session_control_statePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_control_state>,
          )
        >
      >('lenny_session_control_state');
  late final _lenny_session_control_state = _lenny_session_control_statePtr
      .asFunction<
        int Function(
          ffi.Pointer<lenny_session>,
          ffi.Pointer<lenny_control_state>,
        )
      >();

  void lenny_session_destroy(ffi.Pointer<lenny_session> s) {
    return _lenny_session_destroy(s);
  }

  late final _lenny_session_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<lenny_session>)>
      >('lenny_session_destroy');
  late final _lenny_session_destroy = _lenny_session_destroyPtr
      .asFunction<void Function(ffi.Pointer<lenny_session>)>();

  int lenny_session_disconnect(ffi.Pointer<lenny_session> s) {
    return _lenny_session_disconnect(s);
  }

  late final _lenny_session_disconnectPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<lenny_session>)>
      >('lenny_session_disconnect');
  late final _lenny_session_disconnect = _lenny_session_disconnectPtr
      .asFunction<int Function(ffi.Pointer<lenny_session>)>();

  int lenny_session_get_stats(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_stats> out,
  ) {
    return _lenny_session_get_stats(s, out);
  }

  late final _lenny_session_get_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_stats>,
          )
        >
      >('lenny_session_get_stats');
  late final _lenny_session_get_stats = _lenny_session_get_statsPtr
      .asFunction<
        int Function(ffi.Pointer<lenny_session>, ffi.Pointer<lenny_stats>)
      >();

  int lenny_session_peer(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_peer_info> out,
  ) {
    return _lenny_session_peer(s, out);
  }

  late final _lenny_session_peerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_peer_info>,
          )
        >
      >('lenny_session_peer');
  late final _lenny_session_peer = _lenny_session_peerPtr
      .asFunction<
        int Function(ffi.Pointer<lenny_session>, ffi.Pointer<lenny_peer_info>)
      >();

  int lenny_session_set_event_listener(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int32 event,
          ffi.Int32 a,
          ffi.Int32 b,
        )
      >
    >
    fn,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lenny_session_set_event_listener(s, fn, user);
  }

  late final _lenny_session_set_event_listenerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<
              ffi.NativeFunction<
                ffi.Void Function(
                  ffi.Pointer<ffi.Void> user,
                  ffi.Int32 event,
                  ffi.Int32 a,
                  ffi.Int32 b,
                )
              >
            >,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('lenny_session_set_event_listener');
  late final _lenny_session_set_event_listener =
      _lenny_session_set_event_listenerPtr
          .asFunction<
            int Function(
              ffi.Pointer<lenny_session>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void> user,
                    ffi.Int32 event,
                    ffi.Int32 a,
                    ffi.Int32 b,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();

  int lenny_session_state(ffi.Pointer<lenny_session> s) {
    return _lenny_session_state(s);
  }

  late final _lenny_session_statePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<lenny_session>)>
      >('lenny_session_state');
  late final _lenny_session_state = _lenny_session_statePtr
      .asFunction<int Function(ffi.Pointer<lenny_session>)>();

  int lenny_session_stream_settings(
    ffi.Pointer<lenny_session> s,
    ffi.Pointer<lenny_stream_settings> out,
  ) {
    return _lenny_session_stream_settings(s, out);
  }

  late final _lenny_session_stream_settingsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<lenny_session>,
            ffi.Pointer<lenny_stream_settings>,
          )
        >
      >('lenny_session_stream_settings');
  late final _lenny_session_stream_settings = _lenny_session_stream_settingsPtr
      .asFunction<
        int Function(
          ffi.Pointer<lenny_session>,
          ffi.Pointer<lenny_stream_settings>,
        )
      >();
}

const int LENNY_ABI_VERSION_MAJOR = 1;

const int LENNY_ABI_VERSION_MINOR = 3;

const int LENNY_ACK_BUSY = 3;

const int LENNY_ACK_FAILED = 2;

const int LENNY_ACK_OK = 0;

const int LENNY_ACK_UNSUPPORTED = 1;

const int LENNY_CAP_EXPOSURE_COMP = 4;

const int LENNY_CAP_EXPOSURE_LOCK = 8;

const int LENNY_CAP_FOCUS = 1;

const int LENNY_CAP_FOCUS_LOCK = 2;

const int LENNY_CAP_LENS = 64;

const int LENNY_CAP_PAN = 256;

const int LENNY_CAP_TORCH = 32;

const int LENNY_CAP_WB_LOCK = 16;

const int LENNY_CAP_ZOOM = 128;

const int LENNY_CODEC_H264 = 1;

const int LENNY_DEFAULT_PORT = 47474;

const int LENNY_DEVICE_ID_SIZE = 16;

const int LENNY_E_INTERNAL = -4;

const int LENNY_E_INVALID_ARG = -1;

const int LENNY_E_IO = -3;

const int LENNY_E_STATE = -2;

const int LENNY_FRAME_KEYFRAME = 1;

const int LENNY_FRAME_MIRROR = 2;

const int LENNY_MAX_PEER_LENSES = 8;

const int LENNY_MAX_PEER_MODES = 32;

const int LENNY_OK = 0;

const int LENNY_PAIR_ALREADY_USED = 3;

const int LENNY_PAIR_DENIED = 4;

const int LENNY_PAIR_EXPIRED = 2;

const int LENNY_PAIR_OK = 0;

const int LENNY_PAIR_TOKEN_SIZE = 16;

const int LENNY_PAIR_UNKNOWN_TOKEN = 1;

const int LENNY_PLATFORM_ANDROID = 1;

const int LENNY_PLATFORM_IOS = 2;

const int LENNY_PLATFORM_LINUX = 5;

const int LENNY_PLATFORM_WINDOWS = 3;

const int LENNY_REASON_BUSY = 4;

const int LENNY_REASON_LINK_LOST = 100;

const int LENNY_REASON_NORMAL = 0;

const int LENNY_REASON_PAIR_DENIED = 3;

const int LENNY_REASON_PROTOCOL_ERROR = 6;

const int LENNY_REASON_ROLE = 2;

const int LENNY_REASON_TIMEOUT = 5;

const int LENNY_REASON_USER = 7;

const int LENNY_REASON_VERSION = 1;

const int LENNY_STREAM_CAMERA_LOST = 2;

const int LENNY_STREAM_LIVE = 0;

const int LENNY_STREAM_PAUSED = 1;

const int LENNY_STREAM_THERMAL = 3;

final class lenny_control extends ffi.Struct {
  @ffi.Uint32()
  external int req_id;

  @ffi.Uint16()
  external int cmd;

  @ffi.Uint16()
  external int x;

  @ffi.Uint16()
  external int y;

  @ffi.Int32()
  external int value;

  static ffi.Pointer<lenny_control> $allocate(
    ffi.Allocator $allocator, {
    required int req_id,
    required int cmd,
    required int x,
    required int y,
    required int value,
  }) => $allocator<lenny_control>()
    ..ref.req_id = req_id
    ..ref.cmd = cmd
    ..ref.x = x
    ..ref.y = y
    ..ref.value = value;
}

enum lenny_control_cmd {
  LENNY_CTL_KEYFRAME_REQUEST(10),
  LENNY_CTL_FOCUS_AT(11),
  LENNY_CTL_FOCUS_LOCK(12),
  LENNY_CTL_FOCUS_AUTO(13),
  LENNY_CTL_EXPOSURE_COMP(14),
  LENNY_CTL_EXPOSURE_LOCK(15),
  LENNY_CTL_WB_LOCK(16),
  LENNY_CTL_TORCH(17),
  LENNY_CTL_SELECT_LENS(18),
  LENNY_CTL_ZOOM(19),
  LENNY_CTL_RESET_AUTO(20),
  LENNY_CTL_PAN(21);

  final int value;
  const lenny_control_cmd(this.value);

  static lenny_control_cmd fromValue(int value) => switch (value) {
    10 => LENNY_CTL_KEYFRAME_REQUEST,
    11 => LENNY_CTL_FOCUS_AT,
    12 => LENNY_CTL_FOCUS_LOCK,
    13 => LENNY_CTL_FOCUS_AUTO,
    14 => LENNY_CTL_EXPOSURE_COMP,
    15 => LENNY_CTL_EXPOSURE_LOCK,
    16 => LENNY_CTL_WB_LOCK,
    17 => LENNY_CTL_TORCH,
    18 => LENNY_CTL_SELECT_LENS,
    19 => LENNY_CTL_ZOOM,
    20 => LENNY_CTL_RESET_AUTO,
    21 => LENNY_CTL_PAN,
    _ => throw ArgumentError('Unknown value for lenny_control_cmd: $value'),
  };
}

final class lenny_control_state extends ffi.Struct {
  @ffi.Uint8()
  external int af_mode;

  @ffi.Int32()
  external int exposure_comp;

  @ffi.Uint8()
  external int exposure_lock;

  @ffi.Uint8()
  external int wb_lock;

  @ffi.Uint8()
  external int torch;

  @ffi.Uint8()
  external int lens_id;

  @ffi.Uint16()
  external int zoom;

  @ffi.Uint8()
  external int battery;

  @ffi.Uint8()
  external int charging;

  @ffi.Uint16()
  external int pan_x;

  @ffi.Uint16()
  external int pan_y;

  static ffi.Pointer<lenny_control_state> $allocate(
    ffi.Allocator $allocator, {
    required int af_mode,
    required int exposure_comp,
    required int exposure_lock,
    required int wb_lock,
    required int torch,
    required int lens_id,
    required int zoom,
    required int battery,
    required int charging,
    required int pan_x,
    required int pan_y,
  }) => $allocator<lenny_control_state>()
    ..ref.af_mode = af_mode
    ..ref.exposure_comp = exposure_comp
    ..ref.exposure_lock = exposure_lock
    ..ref.wb_lock = wb_lock
    ..ref.torch = torch
    ..ref.lens_id = lens_id
    ..ref.zoom = zoom
    ..ref.battery = battery
    ..ref.charging = charging
    ..ref.pan_x = pan_x
    ..ref.pan_y = pan_y;
}

enum lenny_event {
  LENNY_EVENT_STATE(1),
  LENNY_EVENT_APPROVAL_NEEDED(2),
  LENNY_EVENT_STREAM_START(3),
  LENNY_EVENT_STREAM_STATUS(4),
  LENNY_EVENT_CONTROL_STATE(5),
  LENNY_EVENT_CONTROL_ACK(6);

  final int value;
  const lenny_event(this.value);

  static lenny_event fromValue(int value) => switch (value) {
    1 => LENNY_EVENT_STATE,
    2 => LENNY_EVENT_APPROVAL_NEEDED,
    3 => LENNY_EVENT_STREAM_START,
    4 => LENNY_EVENT_STREAM_STATUS,
    5 => LENNY_EVENT_CONTROL_STATE,
    6 => LENNY_EVENT_CONTROL_ACK,
    _ => throw ArgumentError('Unknown value for lenny_event: $value'),
  };
}

final class lenny_identity extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> device_id;

  external ffi.Pointer<ffi.Char> device_name;

  external ffi.Pointer<ffi.Char> app_version;

  @ffi.Uint8()
  external int platform;
}

final class lenny_lens extends ffi.Struct {
  @ffi.Uint8()
  external int lens_id;

  @ffi.Uint8()
  external int facing;

  external ffi.Pointer<ffi.Char> label;

  static ffi.Pointer<lenny_lens> $allocate(
    ffi.Allocator $allocator, {
    required int lens_id,
    required int facing,
    required ffi.Pointer<ffi.Char> label,
  }) => $allocator<lenny_lens>()
    ..ref.lens_id = lens_id
    ..ref.facing = facing
    ..ref.label = label;
}

final class lenny_lens_caps extends ffi.Struct {
  external ffi.Pointer<lenny_mode> modes;

  @ffi.Size()
  external int mode_count;

  @ffi.Uint16()
  external int zoom_min;

  @ffi.Uint16()
  external int zoom_max;

  @ffi.Uint16()
  external int zoom_base;

  static ffi.Pointer<lenny_lens_caps> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<lenny_mode> modes,
    required int mode_count,
    required int zoom_min,
    required int zoom_max,
    required int zoom_base,
  }) => $allocator<lenny_lens_caps>()
    ..ref.modes = modes
    ..ref.mode_count = mode_count
    ..ref.zoom_min = zoom_min
    ..ref.zoom_max = zoom_max
    ..ref.zoom_base = zoom_base;
}

final class lenny_mode extends ffi.Struct {
  @ffi.Uint16()
  external int width;

  @ffi.Uint16()
  external int height;

  @ffi.Uint16()
  external int fps_num;

  @ffi.Uint16()
  external int fps_den;

  static ffi.Pointer<lenny_mode> $allocate(
    ffi.Allocator $allocator, {
    required int width,
    required int height,
    required int fps_num,
    required int fps_den,
  }) => $allocator<lenny_mode>()
    ..ref.width = width
    ..ref.height = height
    ..ref.fps_num = fps_num
    ..ref.fps_den = fps_den;
}

final class lenny_peer_info extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> device_id;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;

  @ffi.Uint8()
  external int platform;

  @ffi.Uint32()
  external int controls;

  @ffi.Uint8()
  external int lens_count;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> lens_ids;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> lens_facing;

  @ffi.Array.multi([8, 32])
  external ffi.Array<ffi.Array<ffi.Char>> lens_labels;

  @ffi.Int32()
  external int exposure_min;

  @ffi.Int32()
  external int exposure_max;

  @ffi.Uint32()
  external int exposure_step_milli;

  @ffi.Uint8()
  external int mode_count;

  @ffi.Array.multi([32])
  external ffi.Array<lenny_mode> modes;
}

final class lenny_receiver_callbacks extends ffi.Struct {
  external ffi.Pointer<ffi.Void> user;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int32 state,
        ffi.Int32 reason,
      )
    >
  >
  on_state;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<ffi.Uint8> device_id,
        ffi.Pointer<ffi.Char> device_name,
      )
    >
  >
  on_approval_needed;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<lenny_stream_settings> effective,
      )
    >
  >
  on_stream_start;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Uint8 state,
        ffi.Pointer<ffi.Char> reason,
      )
    >
  >
  on_stream_status;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<ffi.Uint8> data,
        ffi.Size size,
      )
    >
  >
  on_video_config;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<lenny_video_frame> frame,
      )
    >
  >
  on_video_frame;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<lenny_control_state> state,
      )
    >
  >
  on_control_state;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Uint32 req_id,
        ffi.Uint8 result,
      )
    >
  >
  on_control_ack;

  static ffi.Pointer<lenny_receiver_callbacks> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> user,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int32 state,
          ffi.Int32 reason,
        )
      >
    >
    on_state,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<ffi.Uint8> device_id,
          ffi.Pointer<ffi.Char> device_name,
        )
      >
    >
    on_approval_needed,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<lenny_stream_settings> effective,
        )
      >
    >
    on_stream_start,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Uint8 state,
          ffi.Pointer<ffi.Char> reason,
        )
      >
    >
    on_stream_status,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<ffi.Uint8> data,
          ffi.Size size,
        )
      >
    >
    on_video_config,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<lenny_video_frame> frame,
        )
      >
    >
    on_video_frame,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<lenny_control_state> state,
        )
      >
    >
    on_control_state,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Uint32 req_id,
          ffi.Uint8 result,
        )
      >
    >
    on_control_ack,
  }) => $allocator<lenny_receiver_callbacks>()
    ..ref.user = user
    ..ref.on_state = on_state
    ..ref.on_approval_needed = on_approval_needed
    ..ref.on_stream_start = on_stream_start
    ..ref.on_stream_status = on_stream_status
    ..ref.on_video_config = on_video_config
    ..ref.on_video_frame = on_video_frame
    ..ref.on_control_state = on_control_state
    ..ref.on_control_ack = on_control_ack;
}

final class lenny_receiver_config extends ffi.Struct {
  external lenny_identity identity;

  @ffi.Uint16()
  external int port;

  external lenny_stream_settings preferred;
}

final class lenny_sender_callbacks extends ffi.Struct {
  external ffi.Pointer<ffi.Void> user;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int32 state,
        ffi.Int32 reason,
      )
    >
  >
  on_state;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<lenny_stream_settings> requested,
        ffi.Pointer<lenny_stream_settings> effective,
      )
    >
  >
  on_stream_config;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Pointer<lenny_control> control,
      )
    >
  >
  on_control;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> user, ffi.Uint32 kbps)
    >
  >
  on_bitrate;

  static ffi.Pointer<lenny_sender_callbacks> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> user,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int32 state,
          ffi.Int32 reason,
        )
      >
    >
    on_state,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<lenny_stream_settings> requested,
          ffi.Pointer<lenny_stream_settings> effective,
        )
      >
    >
    on_stream_config,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<lenny_control> control,
        )
      >
    >
    on_control,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void> user, ffi.Uint32 kbps)
      >
    >
    on_bitrate,
  }) => $allocator<lenny_sender_callbacks>()
    ..ref.user = user
    ..ref.on_state = on_state
    ..ref.on_stream_config = on_stream_config
    ..ref.on_control = on_control
    ..ref.on_bitrate = on_bitrate;
}

final class lenny_sender_config extends ffi.Struct {
  external lenny_identity identity;

  external ffi.Pointer<lenny_mode> modes;

  @ffi.Size()
  external int mode_count;

  @ffi.Uint32()
  external int max_bitrate_kbps;

  @ffi.Uint32()
  external int controls;

  external ffi.Pointer<lenny_lens> lenses;

  @ffi.Size()
  external int lens_count;

  @ffi.Int32()
  external int exposure_comp_min;

  @ffi.Int32()
  external int exposure_comp_max;

  @ffi.Uint32()
  external int exposure_comp_step_milli;

  external ffi.Pointer<lenny_lens_caps> lens_caps;
}

final class lenny_session extends ffi.Opaque {}

enum lenny_state {
  LENNY_STATE_IDLE(0),
  LENNY_STATE_CONNECTING(1),
  LENNY_STATE_HANDSHAKE(2),
  LENNY_STATE_AWAITING_APPROVAL(3),
  LENNY_STATE_STREAMING(4),
  LENNY_STATE_RECONNECTING(5),
  LENNY_STATE_CLOSED(6);

  final int value;
  const lenny_state(this.value);

  static lenny_state fromValue(int value) => switch (value) {
    0 => LENNY_STATE_IDLE,
    1 => LENNY_STATE_CONNECTING,
    2 => LENNY_STATE_HANDSHAKE,
    3 => LENNY_STATE_AWAITING_APPROVAL,
    4 => LENNY_STATE_STREAMING,
    5 => LENNY_STATE_RECONNECTING,
    6 => LENNY_STATE_CLOSED,
    _ => throw ArgumentError('Unknown value for lenny_state: $value'),
  };
}

final class lenny_stats extends ffi.Struct {
  @ffi.Int64()
  external int rtt_us;

  @ffi.Int64()
  external int clock_offset_us;

  @ffi.Uint64()
  external int frames;

  @ffi.Uint64()
  external int bytes;

  @ffi.Uint32()
  external int bad_messages;

  @ffi.Uint32()
  external int reconnects;

  @ffi.Int64()
  external int latency_us;

  @ffi.Uint32()
  external int dropped_frames;

  @ffi.Uint32()
  external int bitrate_kbps;

  static ffi.Pointer<lenny_stats> $allocate(
    ffi.Allocator $allocator, {
    required int rtt_us,
    required int clock_offset_us,
    required int frames,
    required int bytes,
    required int bad_messages,
    required int reconnects,
    required int latency_us,
    required int dropped_frames,
    required int bitrate_kbps,
  }) => $allocator<lenny_stats>()
    ..ref.rtt_us = rtt_us
    ..ref.clock_offset_us = clock_offset_us
    ..ref.frames = frames
    ..ref.bytes = bytes
    ..ref.bad_messages = bad_messages
    ..ref.reconnects = reconnects
    ..ref.latency_us = latency_us
    ..ref.dropped_frames = dropped_frames
    ..ref.bitrate_kbps = bitrate_kbps;
}

final class lenny_stream_settings extends ffi.Struct {
  @ffi.Uint8()
  external int codec;

  external lenny_mode mode;

  @ffi.Uint32()
  external int bitrate_kbps;

  @ffi.Uint8()
  external int has_lens;

  @ffi.Uint8()
  external int lens_id;
}

final class lenny_video_frame extends ffi.Struct {
  @ffi.Uint32()
  external int frame_seq;

  @ffi.Int64()
  external int pts_us;

  @ffi.Int64()
  external int local_pts_us;

  @ffi.Uint8()
  external int orientation;

  @ffi.Uint8()
  external int flags;

  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int size;

  static ffi.Pointer<lenny_video_frame> $allocate(
    ffi.Allocator $allocator, {
    required int frame_seq,
    required int pts_us,
    required int local_pts_us,
    required int orientation,
    required int flags,
    required ffi.Pointer<ffi.Uint8> data,
    required int size,
  }) => $allocator<lenny_video_frame>()
    ..ref.frame_seq = frame_seq
    ..ref.pts_us = pts_us
    ..ref.local_pts_us = local_pts_us
    ..ref.orientation = orientation
    ..ref.flags = flags
    ..ref.data = data
    ..ref.size = size;
}
